services:
  - type: web
    name: ndma-alerts-assistant
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You will manually set it in Render Dashboard
